[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "daphne -b 0.0.0.0 -p 8000 config.asgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10